/*
 This pipeline depicts how an API(project) that is present 
 in VCS can be promoted to an API Gateway Prod environment  after testing it in the 
 API Gateway QA environment.
 The API(project) is imported in the QA environment and after running tests it is promoted
 to the Prod using the Promotion mangement APIs.
 The details of the API Gateway QA environment is provied in the jenkins.properties and the 
 API Gateway Prod environment is created as a stage in the API Gateway QA environment
 The project to be built is provided in jenkins.properties.
 This pipeline by default runs on the master and uses the library methods present in bin/common.lib  
*/

node ("Built-In"){

    def GIT_LOCATION = "https://github.com/analysts-demo/webmethods-api-gateway-devops.git"

	def workspace = pwd()
	def script_location = "${workspace}/apigateway"
	def COMMON_LIB_LOCATION = "${script_location}/bin"
	def TEST_LOCATION = "${script_location}/tests"
	def test_results = "true"
	

	stage('Checkout') {
		 checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'apigateway']], submoduleCfg: [], userRemoteConfigs: [[url: "${GIT_LOCATION}"]]])
	}
	

    load "${script_location}/pipelines/jenkins/jenkins.properties"
	def TEST_API_URL = "${apigateway_qa_url}/gateway/FlipKartProductFeedAPI/feeds/category/TravelAccessories"
	
	stage('Functional tests ') {
		withEnv(["tests_loc=${TEST_LOCATION}/k6","url=${TEST_API_URL}"]) {

			dir("$tests_loc"){		
			  sh '''
				 k6 run -e API_URL=$url functionalTests.js
				 
			   '''
			 }
		  }
	}
	
	
	stage ('Performance Tests') {
		withEnv(["tests_loc=${TEST_LOCATION}/k6","url=${TEST_API_URL}"]) {
			dir("$tests_loc"){
             try {			
			  sh '''
				 k6 run -e API_URL=$url performanceTests.js
			   '''
			   } finally {
			   
			     publishHTML (target: [
					  allowMissing: true,
					  alwaysLinkToLastBuild: false,
					  keepAll: true,
					  reportDir: '.',
					  reportFiles: 'summary.html',
					  reportName: "Performance test report"
					])
				}
			 }
		  }
		  
		  
	}


	stage('Rollout') {
			withEnv(["apigateway_promotion_url=${apigateway_qa_url}/rest/apigateway/promotion","username=${apigateway_qa_username}","password=${apigateway_qa_password}"]) {
						  sh '''
								 curl -X POST -d '{"description": "Promotion Set to promote to Test","name":"PromoteToTest","destinationStages": [	"21e165bd-bffc-4cd9-9d33-52fb81e674f9"],"promotedAssets": {"api": ["a5c09cef-3003-4463-ad58-f49e17fa990f"]}}' -H "Content-Type: application/json" -u $username:$password $apigateway_promotion_url  
						  '''
			}
	}
}